version: "3.9"
services:
  db:
    image: postgres
    ports:
      - 5432:5432

    environment:
      - POSTGRES_DB=testDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres


# services:
#   cache:
#     image: redis:6.2-alpine
#     restart: always
#     ports:
#       - '6379:6379'
#     volumes: 
#       - cache:/data
# volumes:
#   cache:
#     driver: local